#!/bin/bash

#
# Helper script for running barys
#

# Get the absolute script location
pushd `dirname $0` > /dev/null 2>&1
SCRIPTPATH=`pwd`
popd > /dev/null 2>&1

$SCRIPTPATH/barys -k -s -b build --yocto yocto-fido --shared-downloads $SCRIPTPATH/../yocto-fido/shared-downloads --shared-sstate $SCRIPTPATH/../yocto-fido/shared-sstate -l $@
