# private base image requires docker login
FROM balena/balena-img:6.20.26

ARG DEPLOYER_UID
ARG DEPLOYER_GID

# hadolint ignore=DL3008
RUN apt-get update \
    && apt-get install -y --no-install-recommends s4cmd \
    && rm -rf /var/lib/apt/lists/*

RUN groupadd -g $DEPLOYER_GID deployer \
    useradd -m -u $DEPLOYER_UID -g $DEPLOYER_GID deployer
