FROM ubuntu:16.04

RUN apt-get update && apt-get install -y build-essential curl unzip

# Additional host packages required by resin
RUN apt-get update && apt-get install -y apt-transport-https && rm -rf /var/lib/apt/lists/*
RUN curl --silent https://deb.nodesource.com/gpgkey/nodesource.gpg.key | apt-key add -
ENV NODE_VERSION node_8.x
ENV DISTRO xenial
RUN echo "deb https://deb.nodesource.com/$NODE_VERSION $DISTRO main" | tee /etc/apt/sources.list.d/nodesource.list &&\
  echo "deb-src https://deb.nodesource.com/$NODE_VERSION $DISTRO main" | tee -a /etc/apt/sources.list.d/nodesource.list
RUN apt-get update && apt-get install -y jq nodejs sudo && rm -rf /var/lib/apt/lists/*


# Install docker
# https://github.com/docker/docker/blob/master/project/PACKAGERS.md#runtime-dependencies
RUN apt-get update && apt-get install -y iptables procps e2fsprogs xfsprogs xz-utils git kmod && rm -rf /var/lib/apt/lists/*
ENV DOCKER_VERSION 19.03.1

VOLUME /var/lib/docker
RUN curl -sSL https://download.docker.com/linux/static/edge/x86_64/docker-${DOCKER_VERSION}.tgz \
  | tar zx \
  && chmod +x /docker/* \
  && mv /docker/* /usr/local/bin/

# Install balena-cli
ENV BALENA_CLI_VERSION 11.13.1
RUN curl -sSL https://github.com/balena-io/balena-cli/releases/download/v$BALENA_CLI_VERSION/balena-cli-v$BALENA_CLI_VERSION-linux-x64-standalone.zip > balena-cli.zip && \
  unzip balena-cli.zip && \
  mv balena-cli/* /usr/bin && \
  rm -rf balena-cli.zip balena-cli

COPY manage-docker.sh /
COPY start-docker-and-push.sh /
WORKDIR /yocto/resin-board
