ARG NAMESPACE="balena"
ARG TAG="latest"
FROM ${NAMESPACE}/balena-push-env:${TAG}

RUN apt-get update && apt-get install -y git make automake gcc libtool libtool-bin pkg-config libarchive-dev libcurl4-openssl-dev libssl-dev libgpgme11-dev && rm -rf /var/lib/apt/lists/*

RUN git clone git://git.yoctoproject.org/opkg opkg
RUN cd ./opkg && ./autogen.sh && ./configure --enable-libsolv  && make && make install

RUN LD_LIBRARY_PATH=/usr/local/lib && ldconfig

RUN mkdir -p /var/lib/opkg /etc/opkg/
RUN echo 'dest hostapp /hostapp\n\
option info_dir /var/lib/opkg/info\n\
option lists_dir /var/lib/opkg/lists\n\
option status_file /var/lib/opkg/status'\
> /etc/opkg/opkg.conf

COPY include/balena-api.inc include/balena-lib.inc entry_scripts/balena-build-block.sh /
WORKDIR /
